name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/manual-monster-draw ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 24.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm ci

      - name: Build Angular (base-href /)
        run: npm run build -- --configuration production --base-href /

      - name: Add 404.html
        run: |
          mkdir -p dist/gloomhavensecretariat
          cat > dist/gloomhavensecretariat/404.html << 'EOF'
          <!DOCTYPE html><html><head>
          <meta http-equiv="refresh" content="0; url=./index.html">
          </head><body></body></html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/gloomhavensecretariat

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
